### ISSUE TITLE
No student accounts in scoredev

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/katest#2]
Hi @jb-1980 
Two students enrolled today into Math for Financial Literacy A do not have accounts in myedkey activities.  Kindly look into it.

![image](https://user-images.githubusercontent.com/22966552/27359053-7a981e26-55ce-11e7-982e-7cff114124fb.png)
![image](https://user-images.githubusercontent.com/22966552/27359062-8a93d590-55ce-11e7-94ea-fd95e496197f.png)

**Comment by jb-1980** [comment]
The accounts are synced nightly from myedkey. I am seeing this morning that the two students do have accounts, so unless you have manually created them, I am assuming that they were set up from last night's sync.

Also, remember that this is a public repository. So the world now knows Matthew and Andi's email and password.

**Comment by kenburbank** [comment]
Yes I saw that they were set up also.  I just had two go-getters that got to the first KA test on the day they were enrolled.
